package Basic;

public class EE {
public static void main(String[] args) {
	//System.out.println("Hello");
	//System.out.rintln(); // error in 6th line 
	
	
	int a= 10;
	int b=0;
	System.out.println("Welcome");
	
	try 
	{
		System.out.println(a/b); // illegal operation bcz we cant divide any number by 0 // here 11 line will run onlywe3=[vopgp
	
	}
	//catch(Exception e)  // e is reference variable of Exception class
	
	//{
	//	System.out.println("invalid numbers");
	//	e.printStackTrace();
	//}
	
	finally
	{
		System.out.println("This is finally");
	}
	System.out.println("Thank you");
}
}




// 5th oct class









// "try block" trying to run program  if there will exception occures during trying then "catch block" will catch that code
